[package]
name = "rust_apple"
version = "0.1.0"
authors = ["ZDG"]
edition = "2018"

[dependencies]
time = "0.1"

[dependencies.sdl2]
version = "0.34"
default-features = false

[profile.dev]
overflow-checks = false
